apiVersion: v1
kind: Service
metadata:
  name: pytodo-service
spec:
  type: NodePort
  selector:
    app: pytodo
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001  # Port auf deinem Host-Rechner
