apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytodo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytodo
  template:
    metadata:
      labels:
        app: pytodo
    spec:
      containers:
      - name: pytodo
        image: pytodo:latest
        command: ["python"]
        args: ["-u", "pytodo.py"]
        imagePullPolicy: Never
        stdin: true
        tty: true
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "pytododb"
