name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Pull the private Docker image
      run: docker pull ghcr.io/${{ github.repository_owner }}/pytodo:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/pytodo-deployment pytodo=ghcr.io/${{ github.repository_owner }}/pytodo:latest
