name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set lowercase repository owner
      id: repo_owner
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ env.REPO_OWNER }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ env.REPO_OWNER }}/pytodo:latest .
        docker push ghcr.io/${{ env.REPO_OWNER }}/pytodo:latest

    - name: Pull the private Docker image
      run: docker pull ghcr.io/${{ env.REPO_OWNER }}/pytodo:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/pytodo-deployment pytodo=ghcr.io/${{ env.REPO_OWNER }}/pytodo:latest
